services:
  - type: web
    name: propexchange
    env: docker
    plan: free
    rootDir: .             #
    domains:
      - propexchange.rimadagher.ca
    buildCommand: ""
    startCommand: "apache2-foreground"